Add support for writing CSV data sequentially
ImperialCollegeLondon/pycsvy pull request #27
Opened 2023-01-05 14:26 UTC by alexdewar

This PR adds a new `Writer` class, which allows the user to write data sequentially. The problem with the existing code is that all the data must reside in memory before it can be written with write(). For large datasets or those that are being acquired in real time (e.g. from a sensor), this approach doesn't work.

The Writer class provides much the same interface as the writer objects returned from csv.writer. There is also a context manager for automatically closing the file handle.

Closes #13.

2023-01-05 14:27 UTC, alexdewar commented
This PR also needs updating after #24 is merged.

2023-01-24 07:00 UTC, dalonsoa requested changes
Looks great! The only request really is to add tests for all the added functionality (you can see what's missing in the inline comments of the Codecov report).

2023-01-25 14:52 UTC, dalonsoa approved these changes
Looks good! Just a minor comment.

2023-01-25 14:57 UTC, dalonsoa commented
@all-contributors please add @alexdewar  for  test and code

2023-01-25 15:23 UTC, alexdewar commented on csvy/writers.py
> +    def __enter__(self) -> "Writer":
Ahh that's interesting. TIL!

2023-01-25 15:33 UTC, merged