Add flush_immediately to writer.
ImperialCollegeLondon/pycsvy pull request #68
Opened 2023-08-03 14:06 UTC by jamesturner246

Users can specify that the writer should flush after each write operation by setting the optional `flush_immediately` flag true in the writer constructor. Getters and setters also added.

I'm not sure how to easily test that flush has done it's job with pytest, or even if it's possible.

Closes #60

2023-08-03 14:42 UTC, alexdewar requested changes
What I had in mind for this was to set the `buffering` flag in `open` to 1, which automatically flushes the stream with every line: https://docs.python.org/3/library/functions.html#open

2023-08-03 14:49 UTC, jamesturner246 commented
Maybe we can stay flexible and accept the integer flag and pass it as-is to open?

2023-08-03 14:53 UTC, dalonsoa requested changes
Looks good. I've just suggested to remove the setter/getter part, as I feel it is not necessary. 

About testing, it will be necessary to use mocks and check if `flush` is called.

2023-08-03 14:53 UTC, dalonsoa commented on csvy/writers.py
> +        self._flush_immediately = flag
I would not include any setter/getter for this. I wouldn't expect users to change the flush flag midway through the process. If we do want to allow that, just remove the underscore from `self._flush_immediately` and let them change it directly.

2023-08-03 14:54 UTC, dalonsoa commented
I've just seen @alexdewar comment. Yes, if that's possible, it will be simpler, to be honest.

2023-08-03 15:22 UTC, dalonsoa approved these changes
Shorter and simpler 👍

2023-08-03 15:44 UTC, alexdewar approved these changes
LGTM!

2023-08-03 16:09 UTC, merged

2024-10-01 10:09 UTC, dalonsoa commented
@all-contributors please add @jamesturner246 for code